[package]
name = "vault-core"
version = "1.0.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
chacha20poly1305 = "0.10.1"
hkdf = "0.12.4"
rand = "=0.9.2"
sha2 = "0.10.9"
thiserror = "2.0.18"
zeroize = "1.8.2"
zstd = "0.13.3"
