[package]
name = "openvault-sdk"
version = "1.0.0"
edition = "2024"

[dependencies]
openvault-crypto = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
crc32fast = "1.5.0"
byteorder = "1.5.0"
hex = "0.4.3"
postcard = { version = "1.1.3", features = ["use-std"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
walkdir = "2.5.0"
zeroize = { workspace = true, features = ["zeroize_derive"] }

# @todo-now check this..

# regex = "1.11.1"
# fs-err = "2.11.0" # Better fs errors
# file-id = "0.2.2" # For file system identification
# same-file = "1.0.6" # Check if two paths point to same file
# memmap2 = "0.9.5" # Memory mapped I/O
