[package]
name = "openvault-sdk"
version = "0.0.0"
edition = "2024"

[dependencies]
openvault-core = { workspace = true }
openvault-crypto = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
