[package]
name = "openvault-core"
version = "0.0.0"
edition = "2024"

[dependencies]
openvault-crypto = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
crc32fast = "1.5.0"
byteorder = { workspace = true }
hex = "0.4.3"
postcard = { version = "1.1.3", features = ["use-std"] }
serde = { workspace = true, features = ["derive"] }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
validator = { version = "0.20", features = ["derive"] }
walkdir = "2.5.0"
zeroize = { workspace = true, features = ["zeroize_derive"] }
