[package]
name = "openvault-core"
version = "1.0.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
byteorder = "1.5.0"
chacha20poly1305 = "0.10.1"
crc32fast = "1.5.0"
hex = "0.4.3"
hkdf = "0.12.4"
postcard = { version = "1.1.3", features = ["alloc", "use-std"] }
rand = "=0.9.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.10.9"
strum = "0.27.2"
strum_macros = "0.27.2"
thiserror = "2.0.18"
walkdir = "2.5.0"
zeroize = "1.8.2"
zstd = "0.13.3"
