[package]
name = "openvault-secrets"
version = "0.0.0"
edition = "2024"

[dependencies]
chrono = { workspace = true, features = ["serde"] }
openvault-crypto = { workspace = true }
serde = { version = "1.0.228", features = ["derive"] }
postcard = { version = "1.1.3", features = ["alloc", "use-std"] }
thiserror = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
validator = { version = "0.20", features = ["derive"] }
zeroize = { workspace = true, features = ["zeroize_derive"] }
